### ISSUE TITLE
[enhancement] Multiple home user dir

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#325]
**Motivation:**
With multiple home (/home, /home2, /home3 etc) cyberpanel can do storage balance and also will help newbie users that use cloud to avoid have to upgrade their plan to get more storage on main volume. If users can add new homes, it will help them to increase the storage space with simple steps. Additional volumes are cheaper than plan upgrade.

**Tasks:**
- [ ] Identify new /home[0-9]* automatically
- [ ] Allow user to specify the /home/
- [ ] Allow to cyberpanel choose the /home automatically
- [ ] Allow move users between homes

**Comment by usmannasir** [comment]
Possible, but it could take time.

**Comment by ankitsuryawanshi** [comment]
Would love to see this!

**Comment by master3395** [comment]
Trying it out in https://github.com/usmannasir/cyberpanel/pull/1510

**Comment by master3395** [comment]
Thanks for the report. This issue is older and may not apply to current releases.

Please confirm:
1) CyberPanel version + build (please retest on the latest public release **2.4.9**)
2) OS name and version (whatever you run, e.g. `cat /etc/os-release`)
3) Exact steps still failing on a current install
4) Relevant logs (no passwords)

Note: the latest public release is **2.4.9**. Development branches are not recommended for reproducing bugs.

If we do not hear back within 30 days, this issue may be closed as stale. You can reopen with fresh details anytime.
