### ISSUE TITLE
Backup remote transfer bug when one account fail

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#330]
**Problem:**
If one backup fail, you have to reload the remote backup transfer session or other backups actions will fail.

**Steps to reproduce:**

1.  I was moving tree accounts and one of that failed due no free space at remove server to create the backup. The entire process of backup transfer stopped.
2. Then I tried (without reload the backup remote transfer session) to move the other two accounts... the backup was generated on remote server and copied. I do not remember now if I received any message about "successful" message about restoration, but I checked and they not restored. I received some message about "log not found". Sorry, I did not copy the red message that I received, but is something related with missing log file.
3. As I already see some ajax problems on cyberpanel, I tried to reload that session and tried the same two accounts... and it worked.

**Tasks:**
- [ ] Identify why one failed backup will stop the others
- [ ] Try to predict if there is no sufficient space on remote server to create a backup (will avoid problems with old server, also)
- [ ] Identify why the same session can not transfer backups anymore (need to reload the session)

I am using centos 7 updated and cyberpanel v2.0 on both servers.

**Comment by master3395** [comment]
Thanks for the report. This issue is older and may not apply to current releases.

Please confirm:
1) CyberPanel version + build (please retest on the latest public release **2.4.9**)
2) OS name and version (whatever you run, e.g. `cat /etc/os-release`)
3) Exact steps still failing on a current install
4) Relevant logs (no passwords)

Note: the latest public release is **2.4.9**. Development branches are not recommended for reproducing bugs.

If we do not hear back within 30 days, this issue may be closed as stale. You can reopen with fresh details anytime.
